### ISSUE TITLE
Incorrect parameter serializiation

### ISSUE THREAD

**Issue by bezin** [Redocly/redoc#1016]
Hi there,

I currently use the `redoc-cli` to generate an API spec. I have an parameter `id`, that takes an array of UUIDs. 

The spec part:
```      
    parameters:
        - name: id
          in: query
          schema: 
            type: array
            style: form
            explode: true
            maxItems: 50
            items:
              type: string
              format: uuid
            example: 
              - '08759264-10b4-49eb-9d44-bef8080e7922'
              - '08759264-20a4-49eb-9d44-bef8080e7922'
              - '08759264-30a5-49eb-9d44-bef8080e7922'
```

In the HTML output, the example still appears as comma separated values, rather than several chained `id` parameters. 

![190815_120854_EventDB General API Spec 0 2 1](https://user-images.githubusercontent.com/4400435/63088531-7fdfa780-bf55-11e9-96ec-3adc4829371b.png)

Any idea on what could possibly cause this?

Cheers
