### ISSUE TITLE
type array with multiple object

### ISSUE THREAD

**Issue by magicalbanana** [Redocly/redoc#1046]
I have this:

```
        errors:
          type: array
          items:
            - type: object
              properties:
                distance:
                  type: object
                  properties:
                    spheroid:
                      type: object
                      properties:
                        distance:
                          type: string
                          pattern: "^(0{1}|[1-9]([0-9]?)+)(\\.[0-9]{2,6})?$"
                        unit:
                          type: string
                          minLength: 1
                      required:
                        - distance
                        - unit
                      additionalProperties: false
                    longitude:
                      type: object
                      properties:
                        longitude:
                          type: string
                          pattern: "^(\\+|-)?(?:180(?:(?:\\.0{6,15})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{6,15})?))$"
                        distance:
                          type: object
                          properties:
                            distance:
                              type: string
                              pattern: "^(0{1}|[1-9]([0-9]?)+)(\\.[0-9]{2,6})?$"
                            unit:
                              type: string
                          required:
                            - distance
                            - unit
                          additionalProperties: false
                      required:
                        - longitude
                        - distance
                      additionalProperties: false
                  required:
                    - spheroid
                    - longitude
                  additionalProperties: false
              required:
                - distance
              additionalProperties: false
```

But the objects in the array are not being rendered.
![2019-09-26 20:39](https://user-images.githubusercontent.com/7953984/65735668-d6d0b480-e09d-11e9-9c58-48944bc02afb.png)

**Comment by RomanHotsiy** [comment]
OpenAPI 3 doesn't support array in `items`. Is must be object.

Fix by converting items to object:


```yaml
        errors:
          type: array
          items:
            type: object
            properties:
              distance:
                type: object
                properties:
                  spheroid:
                    type: object
                    properties:
                      distance:
                        type: string
                        pattern: "^(0{1}|[1-9]([0-9]?)+)(\\.[0-9]{2,6})?$"
                      unit:
                        type: string
                        minLength: 1
                    required:
                      - distance
                      - unit
                    additionalProperties: false
                  longitude:
                    type: object
                    properties:
                      longitude:
                        type: string
                        pattern: "^(\\+|-)?(?:180(?:(?:\\.0{6,15})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{6,15})?))$"
                      distance:
                        type: object
                        properties:
                          distance:
                            type: string
                            pattern: "^(0{1}|[1-9]([0-9]?)+)(\\.[0-9]{2,6})?$"
                          unit:
                            type: string
                        required:
                          - distance
                          - unit
                        additionalProperties: false
                    required:
                      - longitude
                      - distance
                    additionalProperties: false
                required:
                  - spheroid
                  - longitude
                additionalProperties: false
            required:
              - distance
            additionalProperties: false
```
