### ISSUE TITLE
How can I define how many digitis is allowed behind the comma?

### ISSUE THREAD

**Issue by thanks92** [Redocly/redoc#1055]
How can I specify how many digitis is allowed for decimal part by using OAS 3.0/Redoc?

decimal(10,2) or NUMBER(10,2) means total length is 10 digits but out of 10 digits 2 digits are for decimal part. So the final allowed number will be 8 digits for integral part and 2 digits for fractional part.

**Comment by nanov** [comment]
```yaml
type: number
multipleOf: 0.01
```

**Comment by thanks92** [comment]
If I use mutipleOf it is not visible in the Redoc Document.

```yaml
required:
    - name
properties:
    name:
        type: string
    tag:
        multipleOf: 0.01
        minimum: 0
        type: number
```
![image](https://user-images.githubusercontent.com/8996276/66377764-8832ec80-e9b2-11e9-8bea-810aa42fd299.png)
