### ISSUE TITLE
Options.requiredPropsFirst with SSR results in random property descriptions

### ISSUE THREAD

**Issue by konradbartecki** [Redocly/redoc#1061]
I have noticed that when using --options.requiredPropsFirst and --ssr (so always when bundling) will result in mismatched property descriptions.
Let's say we have 
```
MyRequest:
type: "object"
properties:
  Password:
    type: string
    description: User password
  Login:
    type: string
    description: User login
```

Will result in generated HTML to have <td> where HTML attribute of `Title` is `Password`, but actual description will be `User login`.

Will attach reproduction .yaml later.
