### ISSUE TITLE
Query parameter enum values should not be shown in quotes

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#1085]
Consider the following query parameter:

```yaml
- in: query
  name: "foo"
  schema:
    type: string
    enum:
      - bar
      - baz
```

It is rendered like this:

![image](https://user-images.githubusercontent.com/7766733/67464239-4d33e880-f643-11e9-84e4-df7b17e754f8.png)

I would say that this is incorrect. The values should not be enclosed in quotes (`"`), since the usage is e.g. `?foo=bar`, not `?foo="bar"`.
