### ISSUE TITLE
Don't encode commas in query param examples

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#1092]
Take the following query parameter definition:

```yaml
- in: query
  name: type
  schema:
    type: array
    items:
      type: string
      enum:
        - a
        - b
        - c
    explode: false
    example: "a,b,c"
```

It renders like this:

![image](https://user-images.githubusercontent.com/7766733/68019467-2194ac00-fc9c-11e9-9900-3c8b6b954a1c.png)

While not technically incorrect (I think), it is confusing since basically everywhere else, you'd see it rendered as `type=a,b,c`. Therefore, for clarify, commas should not be encoded in query param examples.

**Comment by TheM1984** [comment]
To be honest I do think that Redoc is rendering incorrectly at this moment.

However if you look at your example you give 1 value, that has comma's within.
You could try the following:

```
- in: query
  name: type
  schema:
    type: array
    items:
      type: string
      enum:
        - a
        - b
        - c
    explode: false
    example:
      - a
      - b
      - c
```
