### ISSUE TITLE
readOnly property is not marked in HTML

### ISSUE THREAD

**Issue by sejvlond** [Redocly/redoc#1097]
Properties marked as `readOnly` are not visually marked as readOnly in HTML see:
![image](https://user-images.githubusercontent.com/5747824/68295646-1b833e80-0093-11ea-95b8-76d37edd78ff.png)

example
```
packets:
    type: integer
    minimum: 0
    readOnly: true 
```

(also they are not present at all in the request, already reported here https://github.com/Redocly/redoc/issues/948)

tested on 2.0.rc14
