### ISSUE TITLE
Empty security array is not supported

### ISSUE THREAD

**Issue by coatesap** [Redocly/redoc#1127]
Where an operation explicitly requires no authentication, the spec says security should be declared as an empty array, eg:

```yaml
paths:
  /login:
    post:
      security: []
```

However, currently Redoc will fall over with the error message "(intermediate value).map is not a function" and not render the docs at all.
