### ISSUE TITLE
YAML Date values without quotes are formatted in ISO datetime format

### ISSUE THREAD

**Issue by matthew-muscat** [Redocly/redoc#1146]
When using redoc-cli, it appears the YAML file is being parsed in JS during the build process — however — we've discovered that when the value is not in quotes, the display in redoc results in the value being displayed in a date-time format.

Strangely — this also appears to occur on string properties, providing the value of the string appears as "2019-12-26" (without quotes)

ie: Object with date property — resulting in "2019-12-23T00:00:00.000Z"

```
type: object
properties:
    delivery_date:
      format: date
      description: An example date.
      type: string
      example: 2019-12-23
```

ie: Object with string property — resulting in "2019-12-23T00:00:00.000Z"

```
type: object
properties:
    delivery_address:
      description: An example field value.
      type: string
      example: 2019-12-23
```
