### ISSUE TITLE
Tag description is generated twice

### ISSUE THREAD

**Issue by bilak** [Redocly/redoc#1150]
Hello,
If I have following in tags 

```
tags:

  - name: "test"
    description: |
      ## This is just test of duplicity
```
Then it's rendered twice:

<img width="470" alt="duplicated-tag" src="https://user-images.githubusercontent.com/5826062/71967504-bc14ec80-3203-11ea-9679-b40068f19e47.png">
