### ISSUE TITLE
Examples appear incorrectly after RC8

### ISSUE THREAD

**Issue by charlesmaragnapm** [Redocly/redoc#1220]
We recently upgraded from RC8 to RC23 (to resolve the sidebar scrolling issue.) We noted that our examples which had originally, appeared like this:
Example: page[number]=1&page[size]=10
now appear like this:
Example: page=page[number]=1&page[size]=10
It would seem this line:
https://github.com/Redocly/redoc/blob/v2.0.0-rc.23/src/utils/openapi.ts#L333
causes the issue.
Is there a way to stop this, or a way we can work around it...
Thanks!

**Comment by RomanHotsiy** [comment]
@charlesmaragnapm could you share a piece of your definition or minimal reproducible sample?

**Comment by charlesmaragnapm** [comment]
Hi @RomanHotsiy 
So this is an example section:

`components:
    schemas:
        query:
            Page:
                type: object
                description: Use pagination when retriving results from the API. When one of these parameters are used, the other is also required.
                example: page[number]=1&page[size]=10
                properties:
                    page[number]:
                        type: integer
                    page[size]:
                        type: integer
                        minimum: 1
                        maximum: 50`

In RC8 this would appear like this:
[https://pasteboard.co/J5S4hns.png](url)

But after updating it looks like this:
[https://pasteboard.co/J5S56PF.png](url)

**Comment by RomanHotsiy** [comment]
RC8 was not spec-compliant.

Use correct `style` and `explode`, see more here: https://swagger.io/docs/specification/serialization/


Here is the snippet which produces the same result as in rc8:

```yaml
      parameters:
        - name: page
          in: query
          description: The user name for login
          required: true
          style: deepObject
          explode: true
          schema:
            type: object
            description: Use pagination when retriving results from the API. When one of these parameters are used, the other is also required.
            example:
              number: 1
              size: 10
            properties:
                number:
                    type: integer
                size:
                    type: integer
                    minimum: 1
                    maximum: 50
```
