### ISSUE TITLE
3rd Level items on left navigation

### ISSUE THREAD

**Issue by lasithalokuge** [Redocly/redoc#1225]
Hi Guys,

Is there any way that I can get a 3rd level on the left navigation. 
![image](https://user-images.githubusercontent.com/13149757/78664075-e1e68600-7905-11ea-92f1-331780291203.png)

I'm using 'x-displayName' and markdown headers to generate 1st level and 2nd level items.
![image](https://user-images.githubusercontent.com/13149757/78664050-d004e300-7905-11ea-8c38-88faa6fe9f48.png)

Thanks

**Comment by lasithalokuge** [comment]
Hi Guys, Any feedback for this?

**Comment by RomanHotsiy** [comment]
There is no way ATM. We will look into this.

**Comment by carlos-moreira** [comment]
@RomanHotsiy 
I don't know if this is related but in my case I'm using the tag grouping feature through the use of 'x-tagGroups', like this:
```
  - name: Facility Management
    tags:
      - customer
      - loan
      - loan-item
      - lost-found
      - lost-found-item
```

I'd like to be able to create sub-groups inside tag groups, like this:
```
x-tagGroups:
  - name: Facility Management
    tags:
      - customer
      x-tagGroups:
      - name: Loan
      tags:
        - loan
        - loan-item
      x-tagGroups:
      - name: Lost Found
        - lost-found
        - lost-found-item
```

That would help a lot with organizing huge docs inside sub-groups of High-level groups.
