### ISSUE TITLE
Examples of a response not rendered when using examples block 

### ISSUE THREAD

**Issue by JanChytry** [Redocly/redoc#1243]
Hey all,

I have encountered an issue in my OAS visualization by redoc, using OpenAPI 3.0.2. 

When using examples block to showcase multiple examples of a single status code in response. It shows example names, however, not the actual examples (is null every time). My spec is the following:

```
      400:
        description: "Polygon does not meet criteria listed above."
        content:
          application/json:
            schema:
              properties:
                message:
                  type: string
            examples:
              PolygonNotValid:
                message: "Polygon format not valid"
              PolygonTooLarge:
                message: "Polygon is too large"
              PolygonNotL2A:
                message: "Polygon has no coverage"
```
![image](https://user-images.githubusercontent.com/24588489/80119931-9f21e080-858a-11ea-898a-609c9a69c1ec.png)

**Comment by RomanHotsiy** [comment]
Valid syntax is:

```yaml
      400:
        description: "Polygon does not meet criteria listed above."
        content:
          application/json:
            schema:
              properties:
                message:
                  type: string
            examples:
              PolygonNotValid:
                value:
                  message: "Polygon format not valid"
              PolygonTooLarge:
                value:
                  message: "Polygon is too large"
              PolygonNotL2A:
                value:
                  message: "Polygon has no coverage"
```

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject
