### ISSUE TITLE
How to render multiple examples in request payload and response body

### ISSUE THREAD

**Issue by snehaa** [Redocly/redoc#1274]
My swagger json has multiple examples which I want to show using Redoc, Open API 3 allows adding multiple examples, but redoc does not render them. 
[Swagger Spec](https://swagger.io/docs/specification/adding-examples/)
but redoc UI shows the payload as one single sample.
Can you suggest how can I display multiple samples.

**Comment by RomanHotsiy** [comment]
Use `examples` property from Swagger spec. Redoc renders them all. If you have issue, could you post minimal reproducible sample?

I will close it, for now, feel free to reopen or continue here.

**Comment by snehaa** [comment]
@RomanHotsiy 
Sorry it is working. I was a spec problem from my side

**Comment by alexlea** [comment]
@snehaa Do you have an example of multiple examples in the request payload that you got working? I've tried every possible combination and the best I can get is a dropdown of the example names with _null_ as the request body

**Comment by duxtinto** [comment]
> @snehaa Do you have an example of multiple examples in the request payload that you got working? I've tried every possible combination and the best I can get is a dropdown of the example names with _null_ as the request body

Hi @alexlea !

Just for the record, I got the same error on the response payload, and this worked for me (basically, I think that the trick was adding the value field):
```
          examples:
            invalid_bank_name:
              value:
                message: 'The given data was invalid.'
                errors:
                  - 'bank_name is not allowed to be empty'
            invalid_file:
              value:
                message: 'The given data was invalid.'
                errors:
                  - 'file is not allowed to be empty'
```

![image](https://user-images.githubusercontent.com/333268/154674107-82f3b03d-7da1-4329-a798-fc170961c59d.png)

Best regards,

David.
