### ISSUE TITLE
oneOf attributes don't display

### ISSUE THREAD

**Issue by Alwyn2000** [Redocly/redoc#1284]
Here is the schema
```
description: |
  Conflict Characteristics:
  - Description of the Conflict Properties
type: object
properties:
  conflictNature:
    description: |
      Conflict Nature:
      Nature of the conflict expressed by a set of properties
    oneOf:
      - $ref: "ConflictA.yaml"
      - $ref: "ConflictB.yaml"
    discriminator:
      propertyName: encounterType
      mapping:
        A_TYPE: "ConflictA.yaml"
        B_TYPE: "ConflictB.yaml"
  conflictClassification:
    description: |
        Severity classification of the conflict
    type: string
    enum:
      - CONFLICT
      - RISK
```
