### ISSUE TITLE
Array of integers does not display the integer limits (maximum/minimum)

### ISSUE THREAD

**Issue by tkarls** [Redocly/redoc#1299]
Consider the following yaml excerpt.
````
        demoArray:
          type: array
          items:
            type: integer
            minimum: 5
            maximum: 10
        demoField:
          type: integer
          minimum: 5
          maximum: 10
````

Redoc reders these as shown

![image](https://user-images.githubusercontent.com/5672845/84490786-f3e8fa00-aca3-11ea-8012-4183c045d142.png)

Ideally the limits [ 5 .. 10 ] would be indicated for the array too.

Like "Array of integers [ 5 .. 10 ]"
