### ISSUE TITLE
`oneOf` + `required` displays not just one property

### ISSUE THREAD

**Issue by aleung** [Redocly/redoc#1334]
### Here is the schema:

``` yaml
components:
  schemas:
    DeviceData:
      type: object
      properties:
        ipv4Addr:
          type: string
        ipv6Addr:
          type: string
        name:
          type: string
      oneOf:
        - required:
            - ipv4Addr
        - required:
            - ipv6Addr
```

### Rendered output:

![Selection_003](https://user-images.githubusercontent.com/271538/89009811-fb419100-d33f-11ea-94f2-8d03fb759e1a.png)
---
![Selection_002](https://user-images.githubusercontent.com/271538/89009805-f7ae0a00-d33f-11ea-9568-5e687a7135fa.png)

### Expected:

When `ipv4Addr` is required, `ipv6Addr` should not exist; when `ipv6Addr` is required, `ipv4Addr` should not exist.

----

I confirmed the schema on https://www.jsonschemavalidator.net/ : `ipv4Addr` and `ipv6Addr` must not present together.
![Selection_004](https://user-images.githubusercontent.com/271538/89010546-6344a700-d341-11ea-856a-6b997c03653c.png)

**Comment by aleung** [comment]
The 3GPP 5G technical specification defines APIs in above style.

Chapter 5.3.14 Attribute Presence Conditions in TS29.501:
https://www.etsi.org/deliver/etsi_ts/129500_129599/129501/15.07.00_60/ts_129501v150700p.pdf

**Comment by RomanHotsiy** [comment]
Properties are defined for the root schema so they show up.

Use this:

```
components:
  schemas:
    DeviceData:
      type: object
      properties:
        name:
          type: string
      oneOf:
        - properties:
            ipv4Addr:
              type: string
           required:
             - ipv4Addr
        - properties:
             ipv6Addr:
               type: string
           required:
             - ipv6Addr
```
