### ISSUE TITLE
Tag Hierarchy using x-tagGroups

### ISSUE THREAD

**Issue by mayurpate** [Redocly/redoc#1370]
I am trying to use x-tagGroups to group my APIs under specific categories. I need to create subGroups of tags under a given group. Something like the following:

```yaml
fruits:
   sweetFruits:
        mango:
        apple:
   bitterFruits:
        orange:
        lemon:
```
I am trying to achieve something like this using YAML written in swagger 2.0.
```yaml
x-tagGroups:
   - name: Fruits
     subGroups:
          - name: sweetFruits
            tags:
               - mango
               - apple
          - name: bitterFruits
            tags:
               - orange
               - lemon
 ```
Is there any way I can achieve this with existing syntax?
