### ISSUE TITLE
Display overriden description of discriminator

### ISSUE THREAD

**Issue by kliput** [Redocly/redoc#1382]
Hello,

Our documentation have a `Caveat` scheme with discriminator named `type`, and number of schemes inheriting from the `Caveat`, eg. `time`, `ip`, `asn`.

The `Caveat` has description of `type` field:
```
properties:
  type:
    type: string
    description: Type of the caveat
```

Every of the sub-scheme has its own description of the `type` field, eg.
```
  properties:
    type:
      type: number
      enum: [time]
      x-discriminator-value: "time"
      description: |
        Time caveat - limits the token's validity in time.
```

In 1.22.3 version of ReDoc, selecting the sub-scheme caused to show its own description of `type` field in request body schema:
![obraz](https://user-images.githubusercontent.com/1345438/92937841-1e398780-f44c-11ea-9735-63461af9bc6f.png)
![obraz](https://user-images.githubusercontent.com/1345438/92937914-36110b80-f44c-11ea-9ca0-df46ef13c205.png)

In 2.x version of ReDoc, only the description defined in `Caveat` is show, no matter which type is selected:
![obraz](https://user-images.githubusercontent.com/1345438/92938281-a6b82800-f44c-11ea-99f9-6f2fd13e5f7d.png)
![obraz](https://user-images.githubusercontent.com/1345438/92938306-addf3600-f44c-11ea-9909-72b0732bf6c4.png)

Is this a missing feature from 1.x or it's possible my schemat is incompatible with new ReDoc?

I'd love to see this supported in 2.x.
