### ISSUE TITLE
Add vendor extension support for API lifecycle annotations

### ISSUE THREAD

**Issue by JSSAggie** [Redocly/redoc#1399]
We use redoc for our internal developer portal as well as our external public-facing developer portal.  We have a need to display additional information about the lifecycle of an API.  We could always add that information in the description but we want more.  We want something more visible and called out.  I am referring to calling them out as annotations.

There are a few ways we can go about this.

1. Add some sort of lifecycle definition and then each operation would define what lifecycles they want to use.
```
x-lifecycleAnnotationSetup:
  - name: Beta
    configuration:
      color: Red
      leftNav: true
  - name: In Development
    configuration:
      color: Blue
      leftNav: true
paths:
  /user:
    post:
      x-lifecycleAnnotations:
        - Beta
```
2. Each operation would define the lifecycle and the definition on each operation.
```
paths:
  /user:
    post:
      x-lifecycleAnnotations:
        - name: Beta
          configuration:
            color: Red
            leftNav: true
```

The result would be something like the image below.  Ignore the mock as we were just hacking around to show an example:
![image-2020-09-30-09-36-23-647](https://user-images.githubusercontent.com/1988405/94724815-74e60300-0320-11eb-969a-e7e63dec56fd.png)

I prefer option 1 but it does include two different vendor extensions.  We would also like to build something that we can give back to the rest of the community.  What are people's thoughts on this and how can we tailor it to meet a more general need?

My team will contribute to this effort but I want to make sure there is a desire to support this type of vendor extension in redoc.
