### ISSUE TITLE
default is missing when combined with allOf

### ISSUE THREAD

**Issue by bburtin** [Redocly/redoc#1409]
When I generate API docs for the following property, ReDoc does not render the `default`:
```
    allOf:
    - type: string
      enum:
      - grow
      - hold
    - default: grow
    - description: allOf is working
```
The `description` is rendered, so I know that it's processing the `allOf`.

![Screenshot from 2020-10-12 13-16-56](https://user-images.githubusercontent.com/5264133/95788054-a26f6c80-0c8f-11eb-96a0-3ca2da43f388.png)
