### ISSUE TITLE
set x-logo image's size in redoc's docker

### ISSUE THREAD

**Issue by handhikadj** [Redocly/redoc#1449]
how do I set the image's width and height while using the docker?

**Comment by lornajane** [comment]
Use the [Redocly CLI docker setup](https://redocly.com/docs/cli/installation/#a-iddockerarun-commands-inside-docker) with a `redocly.yaml` configuration file. In the file, you can set the logo size like this:

```
theme:
  openapi:
    theme:
      logo:
        maxHeight: 120px
        maxWidth: 180px
```

Hope that helps!
