### ISSUE TITLE
Improve order of drop-down items when using discriminator

### ISSUE THREAD

**Issue by henhal** [Redocly/redoc#1462]
When using a `discriminator` for a `oneOf`, field, the order of elements in the drop-down select box seems to be the reverse order of items in the specification. However, the default selected item will be the _first_ specified item.
This is a bit annoying.
Example:

If I have items `APPLES`, `BANANAS` and `CHERRIES` and list them like this:

```
discriminator:
  propertyName: name
  mapping:
    APPLES: ...
    BANANAS: ...
    CHERRIES: ...
```
Then the rendered ReDoc page will have a drop-down with items CHERRIES, BANANAS, APPLES, and the default selected item will be APPLES. 

Sometimes there's an order of items that kind of make sense, so it's a bit annoying that it becomes reversed.

To clarify, I can reverse the items in my specification (even though it's a bit vague to have to order items the opposite order to oblige to the ReDoc renderer:)

```
discriminator:
  propertyName: name
  mapping:
    CHERRIES: ...
    BANANAS: ...
    APPLES: ...
```

Now I'll have a nice APPLES, BANANAS, CHERRIES drop down box, but unfortunately, CHERRIES will be the default item.

Unless it's possible to hint the order and default item, I think a more sensible default ordering would be to list the items as they stand, and use the first item as the default item?
