### ISSUE TITLE
Display error with const

### ISSUE THREAD

**Issue by abersheeran** [Redocly/redoc#1480]
![image](https://user-images.githubusercontent.com/25364828/101606299-30709500-3a3e-11eb-8512-904272f96759.png)

I want it to display the value, but only the type.

![image](https://user-images.githubusercontent.com/25364828/101606329-39f9fd00-3a3e-11eb-9ccb-f90a22c4a88d.png)

**Comment by RomanHotsiy** [comment]
You can use `title` for that:

```yaml
- const: IEP
  type: string
  title: IEP
```
