### ISSUE TITLE
Dockerfile Options

### ISSUE THREAD

**Issue by TLpigff** [Redocly/redoc#1519]
![image](https://user-images.githubusercontent.com/33836582/106854266-f77b3680-66f5-11eb-983a-14747d19a4a1.png)

How to write the OPTIONS environment variable

**Comment by TLpigff** [comment]
I just want to see an example of how to assign, right

**Comment by scottkimGit** [comment]
https://github.com/Redocly/redoc/blob/master/config/docker/index.tpl.html

Learnt that the value of `REDOC_OPTIONS` directly puts into redoc tag attributes

`<redoc spec-url="%SPEC_URL%" %REDOC_OPTIONS%></redoc>`

So, something like `-e REDOC_OPTIONS="hide-download-button=true disable-search=true"` would work

**Comment by milewski** [comment]
Docker composer example:

```yaml
  open-api:
    image: redocly/redoc
    volumes:
      - ./documentation:/usr/share/nginx/html/documentation
    environment:
      SPEC_URL: documentation/OpenAPI.yaml
      REDOC_OPTIONS: >-
        hide-download-button=true
        disable-search=true
```
