### ISSUE TITLE
allOf with polymorphism

### ISSUE THREAD

**Issue by gigaga** [Redocly/redoc#1535]
Hi,

currently, I have an issue about `allOf` usage with a polymorphism object. Indeed, when I use the declaration below, the presentation in redoc is incorrect.

I use Pet object declared like this :

```
  Pet:
        type: object
        required:
        - pet_type
        properties:
          pet_type:
            type: string
          startDate:
            type: string
            example: "2019-11-08"
          num:
            type: integer
            example: 1
        discriminator:
          propertyName: pet_type
          mapping:
            dog: "#/components/schemas/Dog"
            cat: "#/components/schemas/Cat"
            lizard: "#/components/schemas/Lizard"
```

And another object which uses Pet object by adding another property `anotherProperty`
```
  schema:
              x-all-of-name: Page # Force name to avoid warning
              allOf:
              - $ref: ../specs.yaml#/components/schemas/Pet
              - type: object
                properties:
                  anotherProperty:
                    type: string
```

Redoc does not show `anotherProperty` property.

![image](https://user-images.githubusercontent.com/6095992/107975154-f381cb00-6fb7-11eb-9e2d-3ffe3667c876.png)

It is ok in Swagger-UI :

![image](https://user-images.githubusercontent.com/6095992/107975252-23c96980-6fb8-11eb-847a-fd3188df13cf.png)

Regards,
