### ISSUE TITLE
Add description for securitySchemes

### ISSUE THREAD

**Issue by kasperdun** [Redocly/redoc#1619]
![image](https://user-images.githubusercontent.com/15229053/118495829-02098b00-b73d-11eb-9401-468d8e043384.png)

I should add description for securitySchemes, how I can do it?

```
components:
  securitySchemes:
    Bearer:
      $ref: "components/securitySchemes/Bearer.yaml"
    APIKey:
      $ref: "components/securitySchemes/APIKey.yaml"
```
