### ISSUE TITLE
OpenAPI 3.1: Show contentEncoding on fields if present

### ISSUE THREAD

**Issue by mjpieters** [Redocly/redoc#1666]
OpenAPI 3.1 supports JSON Schema `contentEncoding` to mark a field as containing non-string content, see https://json-schema.org/understanding-json-schema/reference/non_json_data.html:

> The `contentEncoding` keyword specifies the encoding used to store the contents, as specified in [RFC 2054, part 6.1.](The contentEncoding keyword specifies the encoding used to store the contents, as specified in RFC 2054, part 6.1.)
>
> The acceptable values are `7bit`, `8bit`, `binary`, `quoted-printable` and `base64`. If not specified, the encoding is the same as the containing JSON document.

The example used in image data, here as JSON:

> ```json
> {
>   "type": "string",
>   "contentEncoding": "base64",
>   "contentMediaType": "image/png"
> }
> ```

We're using `"contentEncoding": "base64",` to handle binary blobs for other purposes in our (non-public) API. However, the ReDoc rendering of the field doesn't reflect this:

```yaml
       body:
          type:
            - string
            - 'null'
          minLength: 0
          maxLength: 100000
          contentEncoding: base64
          pattern: '^[^\0]*$'
```

The field is there but there is no indication that there is a content encoding specified:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/46775/124305937-a9ac1280-db5d-11eb-97fc-9e8e1b1b1ec4.png">

Could this be enhanced to show that the field is expected to use base64 encoding?
