### ISSUE TITLE
Missing highlighting for json, yaml languages

### ISSUE THREAD

**Issue by dbarzdys** [Redocly/redoc#1669]
I'm using latest `redoc-cli` right now to generate docs but when I add code `json` or `yaml` samples in markdown there are no highlight styling on them.

Is there any option to add these languages for styling?

**Comment by saikat-fyers** [comment]
using redoc-cli you are able to build it. ? Let me see the code.

**Comment by dbarzdys** [comment]
Can't share exact code since it is private.

But my setup looks something like this:

#### /openapi.yml

``` yaml
openapi: 3.0.0
info:
  title: Example API
  description:
    $ref: ./README.md
  version: '${version}'
  x-logo:
    url: 'logo.svg'
    backgroundColor: '#FFFFFF'
    altText: "Example"
servers:
  - url: http://localhost:8080
    description: Local

tags:
  - name: echo
    description:
      $ref: ./echo/README.md
    x-displayName: Echo Service

paths:
  # Echo
  /v1/echo:
    $ref: './echo/paths/root.yml'

components:
  schemas:
    $ref: './_schemas.yml'
  securitySchemes:
    $ref: './_security.yml'
```

#### /README.md
~~~  md

### Server Configuration

``` yaml
some:
   # Comment
   parameters: here
```
~~~


#### /echo/README.md
~~~  md

### Echo Service Configuration

``` yaml
some:
   # Comment
   parameters: here
```
~~~

I run this command from my docker image builder stage:

``` sh
sed -i "s/\${version}/${VERSION}/g" openapi.yml \
 && swagger-cli bundle openapi.yml --outfile tmp/openapi.yml --type yaml \
 && redoc-cli bundle -o dist/index.html tmp/openapi.yml 
```

Result builds everything correctly but `yaml` or `json` code blocks from markdown that are placed in description have no highlight styling.

**Comment by flage** [comment]
I have a similar problem. All json, ymal code from markdown files do not have any highlight.

**Comment by RomanHotsiy** [comment]
You should also remove the space before the name of the language:

~~~md
### Echo Service Configuration

``` yaml # <<< here
some:
   # Comment
   parameters: here
```
~~~

should be

~~~md
### Echo Service Configuration

```yaml
some:
   # Comment
   parameters: here
```
~~~
