### ISSUE TITLE
Empty objects with discriminator not showing expand button

### ISSUE THREAD

**Issue by am-houtkooper** [Redocly/redoc#1680]
Suggestion to add a check whether the schema has a discriminator property to mark it as isPrimitive=false:
https://github.com/Redocly/redoc/blob/823be24b313c3a2445df7e0801a0cc79c20bacd1/src/utils/openapi.ts#L114

**Test case**

```yaml
// MyAggregatingField.yaml
type: object
discriminator:
  propertyName: "someType"
  mapping:
    X: X.yaml
    Y: Y.yaml
```

```yaml
// X.yaml
type: object
properties:
  someType:
    type: string
    default: "X"
  foo:
    type: string
```

```yaml
// X.yaml
type: object
properties:
  someType:
    type: string
    default: "Y"
  bar:
    type: string
```
