### ISSUE TITLE
[Bug]: No maxLength label is displayed for arrays of items

### ISSUE THREAD

**Issue by kosanna** [Redocly/redoc#1701]
Hey there, it seems there's some bug with rendering maxLength badges on array of items described by a schema.

Sample json property
```
        "bullets": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 80,
          }
        },
```
Expected behaviour: `<=80 characters` badge is displayed
Actual: 
<img width="530" alt="Screen Shot 2021-07-22 at 4 06 33 pm" src="https://user-images.githubusercontent.com/15971854/126596253-13b3ed11-2547-482e-889b-ee3f589b01d2.png">

`redoc-cli v0.10.4`

Note:
- Could not find anything that says it's been fixed in subsequent version.
- Also could not find any migration guide from 10 to 11, seems to be breaking.

Any advice or help is greatly appreciated. Thank you!

**Comment by ihah** [comment]
Instead of creating new issue just making confirmation on `array` items `string` type rules.
Confirming `redoc-cli v0.12.2` has same behavior, `pattern`, `description`, `minLength`, `maxLength` rule badges are not rendered.
`Enum` rendered.

```yaml
starts:
    type: array
    items:
      type: string
      description: "My start list"
      minLength: 3
      maxLength: 100
    maxItems: 12
```

```yaml
starts:
    type: array
    items:
      type: string
      description: "My start list"
      pattern: /([A-Z])/
    maxItems: 12
```

It seems `enum` rule works:

```yaml
starts:
    type: array
    items:
      type: string
      enum: [Jr. Test, Dr. Tester]
    maxItems: 12
```
![image](https://user-images.githubusercontent.com/35690113/128827255-1ea4d371-9432-45f8-83eb-3fb21a08f978.png)

Maybe `pattern`, `description`, `minLength`, `maxLength` string rules should be rendered same as `enum` rule.

_With `pattern`, `minLength`, `maxLength` string rules_
Items pattern: A-Z
Items length:  [ 3 .. 100 ] characters

_With `maxLength` string rule_
Items length:  <= 100 characters

_With `minLength` string rule_
Items length:  >= 10 characters
