### ISSUE TITLE
[BUG] nullable label not shown

### ISSUE THREAD

**Issue by xYundy** [Redocly/redoc#1702]
When I add `nullable: true` or `x-nullable: true` to property  it doesn't render label in redoc view.

Example (what should be displayed:) https://helpcenter.veeam.com/docs/one/rest/reference/one-rest.html?ver=11

Example of what is displaying now: https://redocly.github.io/redoc/?url=https://helpcenter.veeam.com/content/dam/helpcenter/global/reference/one_rest_110.yaml#operation/About_GetAbout

**Comment by houdinisparks** [comment]
Having this problem after upgrading to redoc version `2.0.0-rc.55` too.
Snippet of specs:

```yaml
...
      properties:
        id:
          type: string
          description: reference id in BGP
          example: 20033TP3
          nullable: true
```

Preview output with `2.0.0-rc.55`:
![image](https://user-images.githubusercontent.com/12453872/126906464-9415d2a7-05a3-4086-a4c4-06dd0666558e.png)

Preview output with `2.0.0-rc.53` (expected output):
![image](https://user-images.githubusercontent.com/12453872/126906472-b31358a4-cc4c-48e1-9a02-42331fdbeb5f.png)
