### ISSUE TITLE
Exapmle for array in query serializes incorrect

### ISSUE THREAD

**Issue by mlonn** [Redocly/redoc#1731]
**Describe the bug**
The examples for an array in query params renders incorrectly
```
        - name: status
          in: query
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              enum: ["PENDING", "IN_PROGRESS", "DELIVERED", "ERROR"]
              example:
               - "PENDING"
               - "IN_PROGRESS"
          description: The kind of consignments that should be returned, if omitted all statuses are returned.
```
renders 
![image](https://user-images.githubusercontent.com/6651453/130811582-47863bfe-0012-4c9d-a3a4-8f7a893e3081.png)

**Expected behavior**
The expected example would be `status=PENDING&status=IN_PROGRESS`
as per https://swagger.io/docs/specification/serialization/

**Additional context**
the explicit definition of style and explode should not be needed either since that is the default. I just added them since the default behavior did not work. 

was supposedly fixed in https://github.com/Redocly/redoc/pull/917
