### ISSUE TITLE
Add descriptions to individual response objects

### ISSUE THREAD

**Issue by Bitz** [Redocly/redoc#1751]
**Describe the problem to be solved**
I would like to be able to describe what the actual response object means. 

**Describe the solution you'd like**
For instance:
![image](https://user-images.githubusercontent.com/2023016/133333138-f2cb626e-3cc0-4f40-9963-8dc8d8e36ffd.png)

In the space shown, I would like to be able to add a description, but currently, even though the `content` supports `description`, the text is not shown.

In the example shown above, the response body looks like:

```yaml
'400':
  description: Bad Request (Validation failure)
  content:
    application/json:
      schema:
        $ref: ..\components\schemas\loi\Response400.yaml
```

And in Response400.yaml:
```yaml
type: object
description: >-
  This is an example, real stuff has been removed.
```

I am not sure if this simply does not work as intended and is therefore a bug, or is something that I am requesting as a new feature.
