### ISSUE TITLE
Using theme in docker

### ISSUE THREAD

**Issue by siarhei-kurhuzenkau-idf** [Redocly/redoc#1787]
Hello,

Following the requests
https://github.com/Redocly/redoc/issues/570
and
https://github.com/Redocly/redoc/pull/1438

I see that there is the theme description in https://redoc.ly/docs/api-reference-docs/configuration/theming/
but it is unclear how to correctly use those options in dockerfile

I tried
REDOC_OPTIONS="disable-search hide-download-button typography.fontsize:"10px" "
and
REDOC_OPTIONS="disable-search hide-download-button theme.typography.fontsize:"10px" "
and
REDOC_OPTIONS="disable-search hide-download-button "theme":{"typography":{"fontSize": "16px"}}"
and
REDOC_OPTIONS="disable-search hide-download-button {"theme":{"typography":{"fontSize": "16px"}}}"

disable-search - works
hide-download-button - works
addressing nested theme json properties does not

Any examples, documentation will be appreciated

**Comment by AlexVarchuk** [comment]
Hello, @siarhei-kurhuzenkau-idf .Thanks for the request.
 Try to pass `theme` object like JSON file
```
REDOC_OPTIONS="disable-search hide-download-button theme='$(<./temp.json)'"
```

temp.json
```
{"typography":{"fontSize": "16px"}}
```

**Comment by AlexVarchuk** [comment]
@siarhei-kurhuzenkau-idf Hi! If you'll have some questions, please reopen this issue. Thanks.

**Comment by ernestomonroy** [comment]
Hi Alex! 

Is there no other way? Something like passing the location of the JSON file.

The problem when doing it via Dockerfile is that you cant set the ENV from the output of a command such as `$(<./temp.json)` or at least not that I know

I see #1047 addresses the JSON string, but not specifically through a JSON file

**Comment by TaTo30** [comment]
This works for me:

theme='{"typography":{"fontSize": "16px"}}'

**Comment by ernestomonroy** [comment]
But this is not setting it from an external file. The problem is reading the file into the variable.

Sorry if this wasn't clear

**Comment by Crateros** [comment]
Wondering about this also, I am running the redocly container via docker compose, trying to get some of the custom options to propagate through ENV variables defined in the `docker-compose.yml` file.

```
  redoc-ui:
    image: redocly/redoc
    ports:
      - 8000:80
    environment:
      SPEC_URL: 'http://localhost:8000/swagger/'
      PAGE_TITLE: 'Test API'
      PAGE_FAVICON: 'https://rainforest.betterworks.com/static/images/favicon.ico'
      REDOC_OPTIONS: 'disable-search hide-download-button theme={"typography":{"fontSize": "16px"}}'
```
disable-search and hide-download-button work, but I cannot get any of the theme properties to apply.
