### ISSUE TITLE
prefixItems isn’t respected

### ISSUE THREAD

**Issue by brookjordan** [Redocly/redoc#1790]
**Describe the bug**

Defining `prefixItems` within an array with `items` set to `false` displays a message saying: `Schema not provided`.

**Expected behavior**

Defining `prefixItems` as an array with `items` set to `false` should outline that this is an array containing only the items in `prefixItems`. Using `anyOf`/`oneOf` as the `items` array gets us a little closer, but doesn’t enforce the order of the items.

This makes it look like the swagger document itself is incorrect. If support of this is out of scope, could we at least change the text to something like “`prefixItems` is not yet supported”?

**Minimal reproducible OpenAPI snippet(if possible)**

```yaml
type: array
minItems: 2
maxItems: 2
prefixItems:
  - number
  - string
items: false
```

**Screenshots**

```yaml
items: false
```
This gives text that blames the author of the swagger document:
<img width="433" alt="Screenshot 2021-11-15 at 5 34 24 PM" src="https://user-images.githubusercontent.com/9323190/141757653-9657d54e-f1ac-45d3-a28a-fbee198ba2df.png">

```yaml
items:
  anyOf:
    - type: number
    - type: string
```
Using `anyOf` or `oneOf` makes it look like the array can be 2 of *either* numbers or strings:
<img width="449" alt="Screenshot 2021-11-15 at 5 40 18 PM" src="https://user-images.githubusercontent.com/9323190/141758557-c0721d88-7535-4089-88f1-04f26358f974.png">
