### ISSUE TITLE
Query parameter default array values not rendered correctly

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#1806]
Consider the following query parameter definition:

```yaml
- in: query
  name: "sort"
  description: |
    ...
  explode: false
  schema:
    type: array
    items:
      type: string
      enum:
        - isPending
        - userFullName
        - email
    default:
      - isPending
      - userFullName
      - email
    example:
      - -isPending
      - email
      - userFullName
```

It is rendered like this:

<img width="997" alt="image" src="https://user-images.githubusercontent.com/7766733/143588285-c48a7fa7-9412-4665-9abe-64e0422af4e1.png">

As you can see, the enumeration and the example renders correctly, but not the default value. It should be rendered like the example, with the query parameter name first and comma between the values.

Workaround: Format manually as string:

```yaml
default: isPending,userFullName,email
```

Using `@next` version from npm.
