### ISSUE TITLE
Support showing SchemaDefinitions in YAML

### ISSUE THREAD

**Issue by codyaray** [Redocly/redoc#1817]
**Describe the problem to be solved**
We're documenting some K8S CRDs using Redoc, but it appears the `<SchemaDefinition>` markdown helper only supports showing the model in JSON, not YAML.

We have entries likes

```
  "tags": [
   {
    "name": "ConfluentRolebinding platform.confluent.io/v1beta1"
    "description": "<SchemaDefinition schemaRef=\"#/components/schemas/io.confluent.platform.api.v1beta1.ConfluentRolebinding\" />",
   }
```
(Note that the K8S CRDs auto-generate swagger (2.0), so this invokes the compatibility layer in Redoc. Hence the above is swagger 2.0 format. I'm not sure this is relevant to the implementation, but just in case)

These show up in the docs like
<img width="1471" alt="Screen Shot 2021-12-01 at 6 04 00 PM" src="https://user-images.githubusercontent.com/44062/144494747-b1d56704-6d9f-40fe-ba5e-53c4eff92b4c.png">

**Describe the solution you'd like**

I'd like this to show the equivalent YAML on the right panel instead, like
```
kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
    name: confluentrolebinding-example
    namespace: confluent
    creationTimestamp: null
spec:
    principal:
        type: user
        name: test
    role: SystemAdmin
status: 
    ...
```

**Describe alternatives you've considered**
No known alternatives

**Additional context**
Many K8S APIs and K8S-inspired APIs prefer YAML content-type. This is both in the model object as well as in requests and responses. I don't know if requests and responses support YAML examples since we're only documenting the CRDs (models) right now. But as we continue working toward more of this "infra-as-code" approach in our APIs, more of them will likely start supporting YAML as well.
