### ISSUE TITLE
How can I show schema description in tags using <SchemaDefinition />

### ISSUE THREAD

**Issue by liao-chenyi-ca** [Redocly/redoc#1840]
I define description in the components.schemas as follows:
```
components:
  schemas:
    some_schema:
      title: some_schema
      type: object
      description: Some Description
      properties:
        param1:
          title: param1
          example: ''
          type: string
```
Then I add the schema in tags:
```
tags:
- name: some_schema
  x-displayName: some_schema
  description: |
    <SchemaDefinition schemaRef="#/components/schemas/some_schema" />
```
But the `description: Some Description` does not show on the webpage.
Is there any way to show the description?

![image](https://user-images.githubusercontent.com/90693309/147017524-dcc9655a-ac43-48e5-841e-28f70f442e53.png)
