### ISSUE TITLE
OpenAPI 3.1 examples not rendered correctly

### ISSUE THREAD

**Issue by kassi** [Redocly/redoc#1905]
**Describe the bug**
Having an array of examples in a schema definition, e.g. under `#/components/schemas` only renders the first one, not all of them.

**Expected behavior**
I expect to see all examples in the right pane.

**Minimal reproducible OpenAPI snippet(if possible)**
```
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
      examples:
        - id: 123
          title: Test title
        - id: 456
          title: Another title
```

**Screenshots**

<img width="1216" alt="Bildschirmfoto 2022-02-14 um 09 18 45" src="https://user-images.githubusercontent.com/993392/153827022-751156dc-ebcc-4815-8591-7cbdc9df17c1.png">

**Additional context**
In openapi 3.1, `example` is deprecated. According to changes from openapi 3.0 to 3.1 (https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) one should use `examples` instead of `example` and add several examples as a list.
It doesn't work either when adding multiple examples to the individual fields instead of the object, i.e.
```
components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          examples:
            - Test title
            - Another title
```
also shows only the first one.

I expect to the all examples either directly listed or selectable (although openapi 3.1 examples are a list, not a hash with keys to select from). Since objects can become complex and properties may depend on each other, showing several real world examples with different use cases make sense.
