### ISSUE TITLE
HTML tags sanitized in arrays with type and format

### ISSUE THREAD

**Issue by cpene1** [Redocly/redoc#1919]
**Describe the bug**
When array items are of specific format (e.g. type "number", format "double"), HTML tags (**`<`** and **`>`**) are sanitized (**`&lt;`** and **`&gt;`**).

**Expected behavior**
HTML tags not being sanitized.

**Minimal reproducible OpenAPI snippet(if possible)**
```
MyResponse:
      required:
      - "someParameter"
      - "otherParameter"
      type: "object"
      properties:
        someParameter:
          type: "array"
          description: "Lorem ipsum."
          items:
            type: "integer"
            format: "int32"
        otherParameter:
          type: "array"
          description: "Lorem ipsum."
          items:
            type: "array"
            items:
              type: "number"
              format: "double"
```
**Screenshots**
![Capture2](https://user-images.githubusercontent.com/59665541/157019506-d6ece565-53be-4f12-814f-6c94d5cffc95.PNG)
