### ISSUE TITLE
Navigation broken when headers share the same name

### ISSUE THREAD

**Issue by cpene1** [Redocly/redoc#1929]
**Describe the bug**
The left-panel navigation is broken if we include headers with the same name in different tags.

**Expected behavior**
The header hyperlinks should point to 2 different id's, even if they share the same name.

**Minimal reproducible OpenAPI snippet(if possible)**

```
tags:
- name: "Tag"
  description: |-
    ## Description
    
    I always get here, even if I press on the Description of "Other Tag" or "Other Tag 2".
- name: "Other Tag"
  description: |-
    ## Description
    
    I can never reach this header (by clicking) through left-panel navigation.
    
    ## Other header
- name: "Other Tag 2"
  description: |-
    ## Description

    I can never reach this header (by clicking) through left-panel navigation.
    
    ## Other header 2
```

**Screenshots**
If needed, I can make a screen recording (since it's hard through a screenshot), but it should be self-explanatory.

**Additional context**
This issue happens because it's not possible to add custom id's on md headers, but they are all generated from the text.
I think a possible solution would be indeed to enable this feature. Long API documentations usually share headers naming, so this problem emerges all the time (e.g. every service might have an "Description" header or "Examples").

Check #1079
