### ISSUE TITLE
Can not read $ref file in properties sometimes.

### ISSUE THREAD

**Issue by fewensa** [Redocly/redoc#1986]
**Describe the bug**
I have two same api, one can read ref and the other can't read it.

**Expected behavior**
should be able to read

**Minimal reproducible OpenAPI snippet(if possible)**

components/schemas/responses/vendor/page.yaml
```
type: object
properties:
  err:
    $ref: ../_common/err.yaml
  data:
    type: object
    properties:
      $ref: ../_common/basic-paged.yaml
      records:
        type: array
        items:
          type: object
          properties:
            $ref: ../_common/basic-vendor.yaml
```

components/schemas/responses/product/page.yaml

```
type: object
properties:
  err:
    $ref: ../_common/err.yaml
  data:
    type: object
    properties:
      $ref: ../_common/basic-paged.yaml
      records:
        type: array
        items:
          type: object
          properties:
            $ref: ../_common/basic-product.yaml
```

components/schemas/responses/_common/basic-vendor.yaml
```
id:
  description: Vendor ID
  type: string
  example: "365764804490694656"
name:
  description: Vendor name
  type: string
  example: Blunk LLC
...
```

components/schemas/responses/_common/basic-product.yaml
```
id:
  description: Product ID
  type: string
  example: "365880768691572736"
vendor_id:
  description: Vendor ID
  type: string
  example: "365764804490694656"
...
```

**Screenshots**

vendor
![image](https://user-images.githubusercontent.com/37804932/167307235-7f1362fe-4e26-4931-ac81-ba9aeaa9ef16.png)

product
![image](https://user-images.githubusercontent.com/37804932/167307219-f1f605c7-b9c5-4f88-9ec9-e8151130f156.png)

**Additional context**

**Comment by AlexVarchuk** [comment]
@fewensa Hi. Thank you for your issue.
I can't reproduce it. Are you sure your definition is valid?
You can check it using CLI.

```bash
npx @redocly/cli lint path-to-root-file.yaml
```

Or maybe your problem is related to $ref sibling. Try to use OpenApi version 3.1.

If none of the above help please provide additional context for reproducing the problem.

**Comment by fewensa** [comment]
Hi @AlexVarchuk , Thanks for your reply. This is my project. you can see that.

paths: https://gitlab.com/repotea-workspace/openapi-camp/-/tree/main/beetle-platform/openapi/paths/product
components/schemas/responses: https://gitlab.com/repotea-workspace/openapi-camp/-/tree/main/beetle-platform/openapi/components/schemas/responses


You can run `npm run start` to see preview page.

**Comment by AlexVarchuk** [comment]
Hi @fewensa, thank you for your example. This definition is not valid we reported it in [cli](https://github.com/Redocly/redocly-cli/issues/682)
For fixing your definition try to use `allOf`.
For example in `openapi/components/schemas/responses/product/page.yaml`

```
type: object
properties:
  err:
    $ref: ../_common/err.yaml
  data:
    type: object
    properties:
      records:
        type: array
        items:
          type: object
          properties:
            $ref: ../_common/basic-product.yaml
    allOf:
      - $ref: ../_common/basic-paged.yaml
```
Also modify `openapi/components/schemas/responses/_common/basic-paged.yaml`.
```
type: object
properties:
  total:
    description: Total data number
    type: number
    example: 1000
  pages:
    description: Total pages
    type: number
    example: 5
...
```
I checked it in your definition.
<img width="1480" alt="Screenshot 2022-05-11 at 18 26 48" src="https://user-images.githubusercontent.com/14113673/167888303-153f60c0-ea8d-4980-b727-4c53054469a6.png">

I hope it helps you.
