### ISSUE TITLE
Handle emtpy object in security array

### ISSUE THREAD

**Issue by gui-camargo** [Redocly/redoc#2074]
**Describe the bug**
The handle (None) that was implemented in fix #1678, no longer works correctly. 
I believe this was caused by feature #2022. 

![image](https://user-images.githubusercontent.com/80956588/177687367-f0f1dd62-482d-46ff-833f-1edf4ac71a61.png)

Expanded:
![image](https://user-images.githubusercontent.com/80956588/177687414-87a8e8be-6b16-41de-8ba6-eb3bf601514b.png)

**Expected behavior**
Show the text "None" (or any other text) when there's an empty security object.

![image](https://user-images.githubusercontent.com/80956588/177687524-47b25fbd-48e3-49b4-a087-07336d2b7350.png)

**Minimal reproducible OpenAPI snippet(if possible)**

```
  /v1/merchant:
    get:
      summary: "Get information of a Merchant"
      security:
        - {}
        - apiKey: []
```
