### ISSUE TITLE
Issue referencing official 2020-12 json meta-schema

### ISSUE THREAD

**Issue by BTOdell** [Redocly/redoc#2158]
**Describe the bug**
I am referencing the official 2020-12 JSON meta-schema in my OpenAPI 3.1 spec:
```yaml
type: object
properties:
  name:
    type: string
  configSchema:
    $ref: "https://json-schema.org/draft/2020-12/schema"
  inputSchema:
    $ref: "https://json-schema.org/draft/2020-12/schema"
  outputSchema:
    $ref: "https://json-schema.org/draft/2020-12/schema"
```

I would expect this to render in some meaningful way with the Redoc UI, but this is what I get:

![image](https://user-images.githubusercontent.com/1644309/189185332-b0fb7ff6-5b9c-4259-8452-a81d00b15c4f.png)

As I understand it, OpenAPI 3.1 is a superset of the 2020-12 JSON Schema specification, so this should work without issue. I see that there are still some on-going issues with full 3.1 support, so maybe there is a simple explanation why this isn't working.

**Expected behavior**

I would expect the redoc tool to render inline documentation for the official JSON Schema spec, or at least provide a link to external documentation (maybe using the `$vocabulary` links embedded in the spec?).

**Comment by AlexVarchuk** [comment]
Hi @BTOdell, thank you for your issue. I think the problem is in your reference link.

Try to run something like this:
```yaml
properties:
  location:
    $ref: 'https://json-schema.org/learn/examples/geographical-location.schema.json'
```
The result is correct:
<img width="889" alt="Screenshot 2022-09-09 at 11 46 03" src="https://user-images.githubusercontent.com/14113673/189311317-1cc9f8c1-fa89-4e7f-885b-350cfb311910.png">

We do not support all keywords from the JsonSchema specification, only most useful for describing API definition. So expected results can be not fully correct.
