### ISSUE TITLE
Nullable array of nullable item is confusingly rendered

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#2260]
I have an array that may be null. The items may also be null.

```yaml
type: array
nullable: true
items:
  type: number
  nullable: true
```

This is rendered like this:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/7766733/216005825-c45e4f57-50de-4c66-96bb-72f028c23af2.png">

The "or null or null" part is confusing. It would be clearer with parentheses: `Array of (numbers or null) or null`
