### ISSUE TITLE
Item minimum/maximum not shown for array of numbers

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#2261]
Consider the following snippet:

```yaml
type: array
nullable: true
items:
  type: number
  nullable: true
  minimum: 1
  maximum: 9
```

It is rendered like this:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/7766733/216006721-9787676f-dc63-4cf1-8e6e-ea61c6270758.png">

The minimum and maximum values are not shown anywhere.
