### ISSUE TITLE
Setting "htmlTemplate" in config is ignored

### ISSUE THREAD

**Issue by hertg** [Redocly/redoc#2290]
> **Note**: This may be slightly related to #2078 

**Describe the bug**
Setting the `htmlTemplate` via config file does not work. This is not due to the config being invalid or not loaded, because changing the `sidebar.backgroundColor` (as shown below) does actually change the output.

```yaml
theme:
  openapi:
    htmlTemplate: ./redocly.html # this setting is ignored
    theme:
      sidebar:
        backgroundColor: '#f2f2f2' # this setting is applied to the output as expected
```

Explicitly setting the `-t` parameter in the command line works as expected.
```
redocly build-docs <yaml> --output <html> -t redocly.html
```

**Expected behavior**
The html template is used when configured via the configuration, as the [documentation](https://redocly.com/docs/api-reference-docs/configuration/functionality/) suggests.

**Additional context**
Installed via `npm i -g @redocly/cli@latest`.

Output of `redocly --version`
```
1.0.0-beta.124
```

**Reproducible**

*./redocly.html*

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>It Works</title>
</head>
<body>
    <h1>If it works, you'll see this text</h1>
</body>
</html>
```

*./redocly.yaml*

```yaml
extends:
  - recommended

theme:
  openapi:
    htmlTemplate: ./redocly.html
```

*Command*

```
redocly build-docs <any-openapi-yaml> --output out.html
```
