### ISSUE TITLE
Render pattern of string in array of strings

### ISSUE THREAD

**Issue by janholusa** [Redocly/redoc#2358]
**Current behavior**
Currently, when there is need of array of strings with regex pattern, e.g.
```json
"MySampleListOfStrings": {
  "type": "array",
  "description": "Some Fancy List of strings with defined pattern which is sadly not visible",
  "items": {
    "type": "string",
    "pattern": "^OMG Nobody can see me regex[0-9]$"
  }
},
```
Pattern itself is not generated:
![image](https://github.com/Redocly/redoc/assets/43773634/b2da0169-9336-49d1-9cf7-097d697cf61e)

**Solution proposal**
Something like this would be good
![image](https://github.com/Redocly/redoc/assets/43773634/e69ff9b4-03f6-4a5b-b287-c73da63ee4b6)

Maybe with brackets, to indicate it is in array.
![image](https://github.com/Redocly/redoc/assets/43773634/610bb8e2-073f-41ae-8265-2a362e8e8ee9)

btw currently it is possible to generate these two samples by using *invalid* schema when pattern is defined for `array`.

```json
"MySampleListOfStrings": {
  "type": "array",
  "pattern": "^OMG Nobody can see me regex[0-9]$",
  "description": "Some Fancy List of strings with defined pattern which is sadly not visible",
  "items": {
    "type": "string"
  }
},
```

**Comment by romanpryshliak** [comment]
Hi @janholusa,

What version of OpenAPI do you have (2.0, 3.0, 3.1, etc.)?

**Comment by janholusa** [comment]
Hi @romanpryshliak ,
I am using `"openapi": "3.0.0",`.

**Comment by UBNT-Peli** [comment]
Unfortunately this bug is still not fully fixed:
- when only pattern is defined it still not render it
```
macList:
  type: array
  description: MAC address list
  items:
    type: string
    pattern: ^([0-9a-f]{2}:){5}[0-9a-f]{2}$
```

- when pattern and minLength/maxLength is defined, it works properly
```
macList:
  type: array
  description: MAC address list
  items:
    type: string
    pattern: ^([0-9a-f]{2}:){5}[0-9a-f]{2}$
    minLength: 17
    maxLength: 17
```
