### ISSUE TITLE
Auto generated examples do not work with exploded array type

### ISSUE THREAD

**Issue by easbar** [Redocly/redoc#2430]
This specification: 

```yaml
        - in: query
          name: my_param
          schema:
            type: array
            items:
              type: string
            example:
              - one
              - two
          explode: true
          style: form
```

correctly yields 

| | |
|-|-|
|my_param|Array of strings<br />Example: my_param=one&my_param=two|

under 'Query Parameters'.

However, in the auto-generated examples we get for example (in Python):

```python
query = {
  "my_param": "my_param=one&my_param=two",
}

response = requests.get(url, params=query)
```

which does not produce a request containing `my_param=one&my_param=two` as url parameters.
