### ISSUE TITLE
Downloading JSON renders empty descriptions for some properties

### ISSUE THREAD

**Issue by monica-m-ps** [Redocly/redoc#2455]
**Describe the bug**
When downloading the JSON, some descriptions aren't rendered at all. But they look fine on the site. (Maybe these descriptions are nested inside nested?)

**Expected behavior**
Descriptions shouldn't be empty

**Minimal reproducible OpenAPI snippet(if possible)**
```
  customerEmail:
    nullable: true
    oneOf:
      - $ref: ./PaymentIntentConfigCustomerEmail.yaml
    description:   
      $ref: ../../../prose/parameters/customerEmail.md
```

`paymentIntentConfigCustomerEmail` looks like:

```
type: object
additionalProperties: false
title: PaymentIntentConfigCustomerEmail
description: ''
properties:
  collectionRequired:
    type: boolean
    description:    
      $ref: ../../../prose/parameters/collectionRequired.md
    default: false

```

**Screenshots**
<img width="871" alt="image" src="https://github.com/Redocly/redoc/assets/94380874/25fe01c2-606e-40be-8f74-7d8bd81acae7">

<img width="584" alt="image" src="https://github.com/Redocly/redoc/assets/94380874/98675306-6976-4d80-b944-a591c6099c7c">

**Additional context**
<img width="648" alt="image" src="https://github.com/Redocly/redoc/assets/94380874/33c76305-b70c-472f-a166-863fbe8c254a">

Can someone please help me here?

**Comment by romanpryshliak** [comment]
Hello @monica-m-ps,

I noticed that within the snippets provided, two properties `customerEmail` and `collectionRequired` have descriptions matching what's shown in the screenshots. I have also noticed that the `paymentIntentConfigCustomerEmail` schema lacks a description in both the snippet and the screenshot.

Based on this, could you please specify which description exactly is missing after the file is downloaded? If there's publicly accessible documentation showcasing this issue, could you kindly provide a link to it?

**Comment by jeremyfiel** [comment]
@monica-m-ps  can this be closed?

**Comment by monica-m-ps** [comment]
Yes please. Sorry there are still discussions going on within the team here. 
@romanpryshliak : This is currently live on docs.dojo.tech/api.

@jeremyfiel Thanks for this solution. If I'll need to ask anything else, I'll post it again. Thank you!

**Comment by jeremyfiel** [comment]
@monica-m-ps   Are you still having some issue with the description populating? I don't see it on the link you provided. 

I think I misunderstood your usage of `oneOf`.  You should be able to get the description without the `oneOf`. 

```yaml
 customerEmail:
    nullable: true
    allOf:
      - $ref: ./PaymentIntentConfigCustomerEmail.yaml
      - description:   
          $ref: ../../../prose/parameters/customerEmail.md
```
