### ISSUE TITLE
Schemas based on ref get incorrectly replace at bundle time

### ISSUE THREAD

**Issue by jeluard** [Redocly/redoc#2480]
**Describe the bug**

A schema referencing another schema via ref will get incorrectly replaced when bundling.

e.g.

```yaml
Uint64:
  type: string
  example: "1"

GenesisTime:
  $ref: "./primitive.yaml#/Uint64"
  example: "1590832934"
  description: "The genesis_time configured for the beacon node, which is the unix time in seconds at which the Eth2.0 chain began."

...
properties:
  genesis_time:
    $ref: '../../beacon-node-oapi.yaml#/components/schemas/GenesisTime'
```

will generate 

```yaml
genesis_time:
  type: string
  example: '1'
```

**Expected behavior**

I would expect the following to be generated. `swagger-cli` does.

```yaml
genesis_time:
  type: string
  example: '1590832934'
  genesis: 'The genesis_time configured for the beacon node, which is the unix time in seconds at which the Eth2.0 chain began.'
```
