### ISSUE TITLE
minLength/maxLength not shown for array items with pattern

### ISSUE THREAD

**Issue by P-Lng** [Redocly/redoc#2544]
An array item that has `pattern` and `minLength`/`maxLength` defined, only shows `pattern`.
Plain properties behave as expected, they display both.

![image](https://github.com/Redocly/redoc/assets/39089684/b82d820d-89d1-4ada-a499-478ccf35c825)

**Expected behavior**
Show all restrictions: `Array of strings [[ 1 .. 10 ] characters ^[A-Z]+$]`

**Minimal reproducible OpenAPI snippet**
```YAML
properties:
  plain_property:
    type: string
    pattern: '^[A-Z]+$'
    minLength: 1
    maxLength: 10
  array_items:
    type: array
    items:
      type: string
      pattern: '^[A-Z]+$'
      minLength: 1
      maxLength: 10
```
