### ISSUE TITLE
Show all components in the UI

### ISSUE THREAD

**Issue by agaro1121** [Redocly/redoc#2565]
Hello!

I built an html static page with the `build-docs` command but it only shows the schemas for the request/responses. Is there a way to show all the components on the sidebar separate from the endpoints?

**Comment by AlexVarchuk** [comment]
Hi @agaro1121, Sorry for long delay.
Try to use `<SchemaDefinition/>` component in `tags` or `info->description`
For exmaple:

```
tags:
  - name: pet_model
    x-displayName: The Pet Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Pet" />
```

Please reopen that issue if you have more questions. Thanks
