### ISSUE TITLE
hideRightPanel configuration does not have any effect

### ISSUE THREAD

**Issue by lcdunne** [Redocly/redoc#2566]
I am trying out redocly via the cli. I was testing out some of the configurations and noticed that the `hideRightPanel` option does not seem to have any effect.

To reproduce: create a `redocly.yaml`:
```yaml
theme:
  openapi:
    disableSearch: true
    hideRightPanel: true
```

Then run `redocly build-docs openapi.yaml` and view the resulting html page

I was expecting the entire right panel to disappear but it did not. The configuration appears to be correct as the `disableSearch` works, and there are no errors or warnings in the terminal.

I'm using redocly version 1.18.1 and node v20.10.0.
