### ISSUE TITLE
Better Presentation of Maximum and Minimum String Length

### ISSUE THREAD

**Issue by APIWriter** [Redocly/redoc#2630]
**Describe the bug**
I don't like the way minimum and maximum string lengths are presented. They are seen as an unlabeled array such a [5 .. 10]. It's not clear at one glance what the notation even refers to.
![Image](https://github.com/user-attachments/assets/90f9c84c-279c-4e62-8392-036b28acfe05)

**Expected behavior**
A more precise presentation would be to label each one explicitly:
Minimum length: 0
Maximum length: 5

**Minimal reproducible OpenAPI snippet(if possible)**
The coding is good, just not the rendering.
```
        zip_code:
          type: string
          minimum: 5
          maximum: 10
          nullable: true
          description: |
            Specifies the ZIP or postal code of the receiving destination.
          example: '91104'
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/90f9c84c-279c-4e62-8392-036b28acfe05)

**Additional context**

**Comment by AlexVarchuk** [comment]
It looks like the same to me https://github.com/Redocly/redoc/issues/2630.

**Comment by APIWriter** [comment]
Hi Alex,

Thanks for looking into this. I am the author of #2630<https://github.com/Redocly/redoc/issues/2630> and #263<https://github.com/Redocly/redoc/issues/2630>1.

The two aren't the same although they are related.

#2630<https://github.com/Redocly/redoc/issues/2630> is that I don't like the presentation of string minimum and maximum lengths. I'm suggesting they be explicitly labeled.

#263<https://github.com/Redocly/redoc/issues/2630>1 is for a odd situation. An optional string field, for example, should have a minimum length of zero, it is optional after all. However, if a field value is provided, it might have a new minimum length of five. Is there a way of marking that in Redocly rather than commenting it in the description?
________________________________

**Comment by AlexVarchuk** [comment]
Sorry I put the wrong link. Updated and added comment to that https://github.com/Redocly/redoc/issues/2631#issuecomment-2565786502.
I believe these cases related to same options(`minimum/maximum`) and how render that field. No reason to have separate issue for that.

**Comment by jeremyfiel** [comment]
I think your interpretation of `null` is slightly different than what is defined in OpenAPI or JSON Schema. Optionality has nothing to do with the validation results other than when the `required` keyword is used. 

`null` equates to a field with a _null_ value 

```yaml
# valid
test: null
```

that is different than empty

```yaml
# invalid
test: ""
```

the validation for string fields only activates when a string value is defined.  empty or otherwise but **not** with the `null` value. 

Based on the constraints you have `[5, 10]` and `nullable: true`

```yaml
# valid
test: null

# valid
test: letters

# invalid
test: ""

# invalid
test: five

# invalid
test: areallylongstring
```
