### ISSUE TITLE
"API docs by Redocly" banner at the bottom of the sidebar can obstruct the last item inside the sidebar

### ISSUE THREAD

**Issue by svix-jplatte** [Redocly/redoc#2650]
**Describe the bug**

When the browser viewport is not high enough to fit the entire sidebar contents, the last item gets hidden behind the "API docs by Redocly" banner at the bottom of the sidebar.

**Expected behavior**

All sidebar items should be visible

**Screenshots**

![Image](https://github.com/user-attachments/assets/0a2f1a19-3d99-427d-8353-cbde5d177d95)

**Additional context**

I worked around the issue by including this extra bit of CSS to our site:

```css
redoc ul[role="menu"] {
    /* fix last item being hidden behind the redoc banner on smaller viewports */
    padding-bottom: 32px;
}
```
