### ISSUE TITLE
Oneof and nullable cannot be used in OpenAPI 3.0 and an error occurs

### ISSUE THREAD

**Issue by jsakaicribl** [Redocly/redoc#2670]
**Describe the bug**

I think the following is correct in OpenAPI 3.0, but I get an error. It seems to not able to use oneOf and `nullable`.
```
        - type: object
          properties:
            earliest:
              oneOf:
                - type: string
                  nullable: true
                - type: number
                  nullable: true
```
Error is:
```
Property `nullable` is not expected here.

2089 | oneOf:
2090 |   - type: string
2091 |     nullable: true
     |     ^^^^^^^^
2092 |   - type: number
2093 |     nullable: true

Error was generated by the struct rule.
```
I put nullable outside oneOf, but I get an error.
```
 - type: object
          properties:
            earliest:
              oneOf:
                - type: string
                - type: number
              nullable: true
```
I also get an error when using anyOf.
```
        - type: object
          properties:
            earliest:
              anyOf:
                - type: string
                - type: number
              nullable: true
```

**Expected behavior**
There should be no error.

**Minimal reproducible OpenAPI snippet(if possible)**
The command is as follows, 
```
docker run --rm -v $PWD:/spec redocly/cli lint openapi.yaml
```
