### ISSUE TITLE
Discriminated schema with shared ancestor shows invalid mapping options

### ISSUE THREAD

**Issue by milesizzo** [Redocly/redoc#2678]
**Describe the bug**

If a discriminated schema shares a common ancestor (schema) with another discriminated schema, extra schemas are shown in the UI (namely the two discriminated schemas).

**Expected behavior**

I would expect only the types listed in the mapping section to be shown.

**Minimal reproducible OpenAPI snippet(if possible)**

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "v1"
  },
  "paths": {
    "/animals": {
      "post": {
        "summary": "Create an animal",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAnimalReqDto"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateAnimalReqDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "mammal": {
            "$ref": "#/components/schemas/MammalDto"
          },
          "reptile": {
            "$ref": "#/components/schemas/ReptileDto"
          }
        }
      },
      "AnimalDto": {
        "type": "object"
      },
      "MammalDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AnimalDto"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              }
            },
            "discriminator": {
              "propertyName": "type",
              "mapping": {
                "cat": "#/components/schemas/CatDto",
                "dog": "#/components/schemas/DogDto"
              }
            }
          }
        ]
      },
      "ReptileDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AnimalDto"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              }
            },
            "discriminator": {
              "propertyName": "type",
              "mapping": {
                "lizard": "#/components/schemas/LizardDto"
              }
            }
          }
        ]
      },
      "CatDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/MammalDto"
          },
          {
            "type": "object"
          }
        ]
      },
      "DogDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/MammalDto"
          },
          {
            "type": "object"
          }
        ]
      },
      "LizardDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/ReptileDto"
          },
          {
            "type": "object"
          }
        ]
      }
    }
  }
}
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/f68b3a0e-5179-4f04-971e-ac90015c119f)

(highlighted discriminator values are invalid)

**Additional context**

N/A

**Comment by milesizzo** [comment]
I assume this is the same issue, but will document it here anyway. Using `AnimalDto` as the base discriminated type and `MammalDto`/`ReptileDto` as intermediate types:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "v1"
  },
  "paths": {
    "/animals": {
      "post": {
        "summary": "Create an animal",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAnimalReqDto"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateAnimalReqDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "animal": {
            "$ref": "#/components/schemas/AnimalDto"
          }
        }
      },
      "AnimalDto": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "type",
          "mapping": {
            "cat": "#/components/schemas/CatDto",
            "dog": "#/components/schemas/DogDto",
            "lizard": "#/components/schemas/LizardDto"
          }
        }
      },
      "MammalDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AnimalDto"
          },
          {
            "type": "object"
          }
        ]
      },
      "ReptileDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/AnimalDto"
          },
          {
            "type": "object"
          }
        ]
      },
      "CatDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/MammalDto"
          },
          {
            "type": "object"
          }
        ]
      },
      "DogDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/MammalDto"
          },
          {
            "type": "object"
          }
        ]
      },
      "LizardDto": {
        "allOf": [
          {
            "$ref": "#/components/schemas/ReptileDto"
          },
          {
            "type": "object"
          }
        ]
      }
    }
  }
}
```

Produces the following UI:

![Image](https://github.com/user-attachments/assets/9b191b88-9561-4dfa-96c0-a17a8ae21bce)

**Comment by milesizzo** [comment]
Perhaps this is my misunderstanding of how to structure a polymorphic schema:

> I assume this is the same issue, but will document it here anyway. Using `AnimalDto` as the base discriminated type and `MammalDto`/`ReptileDto` as intermediate types:

Using this example, I removed the inclusion of `AnimalDto` from `MammalDto` and `ReptileDto`:

```yaml
// ... snip ...
      "AnimalDto": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "type",
          "mapping": {
            "cat": "#/components/schemas/CatDto",
            "dog": "#/components/schemas/DogDto",
            "lizard": "#/components/schemas/LizardDto"
          }
        }
      },
      "MammalDto": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          }
        }
      },
      "ReptileDto": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          }
        }
      },
// ... snip ...
```

This produced the correct result:

![Image](https://github.com/user-attachments/assets/595bf9fd-d779-4d05-af5e-7ba6704e06c3)

Albeit at the expense of redefining common properties in each mapped schema.
