### ISSUE TITLE
Add dynamic values to x-code-samples

### ISSUE THREAD

**Issue by lcofre** [Redocly/redoc#365]
The source field on the x-code-samples is a literal text. It would be great to add variables defined on the Swagger schema, i.e. basePath and host.

Having said that, thanks very much for his great user interface! It is really intuitive and configurable. :)

**Comment by RomanGotsiy** [comment]
@lcofre thanks for the suggestion and for kind words!

This is a completely valid use case and a great feature.
Let's get back to this after 2.0 is released.

**Comment by SangHakLee** [comment]
@lcofre Is this your suggestion?

Now my `x-code-samples`
```yaml
# dev server
x-code-samples:
    - lang: PHP
      source: |
        <?php
        $host = "http://dev.com"
    - lang: Node.js
      source: |
        let host = "http://dev.com"

# production server
x-code-samples:
    - lang: PHP
      source: |
        <?php
        $host = "http://prod.com"
    - lang: Node.js
      source: |
        let host = "http://prod.com"
```

I really want like this, @RomanGotsiy 
```yaml
# HOST= "http://dev.com" or "http://prod.com"

x-code-samples:
    - lang: PHP
      source: |
        <?php
        $host = "${HOST}"
    - lang: Node.js
      source: |
        let host = "${HOST}"
```
