### ISSUE TITLE
Render array/object examples correctly according to style/explode

### ISSUE THREAD

**Issue by cmeeren** [Redocly/redoc#504]
Parameter examples should render correctly based on the `style` and `explode` fields.

For example, consider this parameter definition:

```yaml
parameters:
  - in: query
    name: scopes
    description: A comma-separated list of scopes
    schema:
      type: array
      items: string
    style: form
    explode: false
    example:
      - foo
      - bar
```

This currently renders like this:

![image](https://user-images.githubusercontent.com/7766733/40471373-c925602c-5f36-11e8-936f-73e1ede93e98.png)

I would expect the example to render like `foo,bar` (also without quotes).

A possible workaround would be to write `example: foo,bar`, but this renders as `"foo,bar"` with quotes, which is incorrect since it's a query parameter. So there's no workaround I know of to correctly display an example for a query string, except manually writing an example in the `description`.

Further reading: https://swagger.io/docs/specification/serialization
