### ISSUE TITLE
Parameters are not displayed correctly for complex serialization scenarios

### ISSUE THREAD

**Issue by fredriklengstrand** [Redocly/redoc#606]
When describing the parameter contents using the `content` keyword (to handle [complex serialization](https://swagger.io/docs/specification/describing-parameters/#schema-vs-content) scenarios) the parameters are not shown correctly in the UI (wrong type and not expandable):

<img width="654" alt="screen shot 2018-08-14 at 20 09 52" src="https://user-images.githubusercontent.com/10126466/44109734-0af0dac4-9ffe-11e8-9430-799f68a5fbb3.png">

Here is the code example they used in the link above which should be valid in OpenAPI 3:

```
parameters:
  - in: query
    name: filter
    content:
      application/json:
        schema:
          type: object
          properties:
            type:
              type: string
            color:
              type: string
```

If you remove the `content` and `application/json` keywords that are wrapped around the parameters they are shown correctly (but then it's no longer according to spec for these specific scenarios):

<img width="644" alt="screen shot 2018-08-14 at 20 11 50" src="https://user-images.githubusercontent.com/10126466/44109822-4e2ba210-9ffe-11e8-9dc9-d658c3708d10.png">
