### ISSUE TITLE
References are not fully dereferenced

### ISSUE THREAD

**Issue by MaSpeng** [Redocly/redoc#749]
When using the redoc-cli in conjunction with a `yaml` definition which highly depends on references for reusable elements, not all references will be dereferenced.

Right after the first and the last pass of `loadAndBundleSpec` there are invalid resolved references:

Example part of the source yaml files:
```yaml
# ...
401:
  $ref: "../../../components/responses.yaml#/responses/json_api_401"
403:
  $ref: "../../../components/responses.yaml#/responses/json_api_403"
500:
  $ref: "../../../components/responses.yaml#/responses/json_api_500"
# ...
```

Response definition:
```yaml
# ...
json_api_401:
  description:
    $ref: "#/components/description_401"
  headers:
    $ref: "headers.yaml#/headers/content_type_json_api"
  content:
    $ref: "#/components/content_401"

json_api_403:
  description:
    $ref: "#/components/description_403"
  headers:
    $ref: "headers.yaml#/headers/content_type_json_api"
  content:
    $ref: "#/components/content_403"

json_api_500:
  description:
    $ref: "#/components/description_500"
  headers:
    $ref: "headers.yaml#/headers/content_type_json_api"
  content:
    $ref: "#/components/content_500"
# ...
```

Content and description definition:
```yaml
# ...
description_401: Unauthorized

content_401:
  application/json:
    schema:
      $ref: "http://jsonapi.org/schema#/definitions/failure"
    example: {
      "errors": [
      {
        "status": "401",
        "title": "Bad credentials",
        "detail": "Bad credentials, an access token is required"
      }
      ]
    }

description_403: Forbidden

content_403:
  application/json:
    schema:
      $ref: "http://jsonapi.org/schema#/definitions/failure"
    example: {
      errors: [
      {
        "status": "403",
        "title": "Forbidden",
        "detail": "Access denied"
      }
      ]
    }

description_500: Internal Server Error

content_500:
  application/json:
    schema:
      $ref: "http://jsonapi.org/schema#/definitions/failure"
    example: {
      "errors": [
      {
        "status": "500",
        "title": "JWT creation failed",
        "detail": "JWT library failed to create an access token"
      }
      ]
    }
# ...
```

Headers defintion:
```yaml
# ...
content_type_json_api:
  Content-Type:
    description: The json api content-type header
    schema:
      type: string
    example: application/vnd.api+json
# ...
```

Example part of resulting json:
```json
{
  "401": {
    "description": "Unauthorized",
    "headers": {
      "$ref": "#/paths/~1rest~1authorized~1workplaces%7B%3Ffilter*%2Cpage%2Climit%7D/get/responses/500/headers"
    },
    "content": {
      "application/json": {
        "schema": {
          "$ref": "#/paths/~1rest/get/responses/500/content/application~1vnd.api%2Bjson/schema"
        },
        "example": {
          "errors": [
            {
              "status": "401",
              "title": "Bad credentials",
              "detail": "Bad credentials, an access token is required"
            }
          ]
        }
      }
    }
  },
  "403": {
    "description": "Forbidden",
    "headers": {
      "$ref": "#/paths/~1rest~1authorized~1workplaces%7B%3Ffilter*%2Cpage%2Climit%7D/get/responses/500/headers"
    },
    "content": {
      "application/json": {
        "schema": {
          "$ref": "#/paths/~1rest/get/responses/500/content/application~1vnd.api%2Bjson/schema"
        },
        "example": {
          "errors": [
            {
              "status": "403",
              "title": "Forbidden",
              "detail": "Access denied"
            }
          ]
        }
      }
    }
  },
  "500": {
    "description": "Internal Server Error",
    "headers": {
      "Content-Type": {
        "description": "The json api content-type header",
        "schema": {
          "type": "string"
        },
        "example": "application/vnd.api+json"
      }
    },
    "content": {
      "application/json": {
        "schema": {
          "$ref": "#/paths/~1rest/get/responses/500/content/application~1vnd.api%2Bjson/schema"
        },
        "example": {
          "errors": [
            {
              "status": "500",
              "title": "JWT creation failed",
              "detail": "JWT library failed to create an access token"
            }
          ]
        }
      }
    }
  }
}
```

The source of this issue seems to be related to the depth and count of the reference. As you can see, the last response definition also contains a content-type header definition. This one is correctly resolved, the other ones in the same time are not.
