### ISSUE TITLE
Keep property order when merging with oneOf

### ISSUE THREAD

**Issue by unional** [Redocly/redoc#759]
# Input

```yaml
components:
  schema:
    abc:
      type: object
      properties:
        '@id': ...
        description: ...
      oneOf:
        - title: option1
           properties:
             propA: ...
             propB: ...
        - title: option2
           properties:
             propX: ...
             propY: ...
```

# expected behavior

```
// displayed as in Redoc:
One of [Option1] [Option2] // example with Option1 selected
- '@id'
- description
- propA
- propB
```

# actual behavior

```
// displayed as in Redoc:
One of [Option1] [Option2] // example with Option1 selected
- propA
- propB
- '@id'
- description
```
