### ISSUE TITLE
External schema is displayed finely but external securitySchema is not 

### ISSUE THREAD

**Issue by exoego** [Redocly/redoc#819]
* redoc: `v2.0.0-rc.2`
* openapi: `3.0.0`

I have several swagger.yml.
To minimize duplicative definition in those, I defined `common.yml` and refer it from other `swagger.yml`.

`components` section of common.yml are something like 

```yml
components:
  schemas:
    FooBar:
      type: string
      enum:
      - foo
      - bar
  securitySchemes:
     AuthHeader:
      description: example
      type: "apiKey"
      name: "Authorization"
      in: "header"
```

And usage in separate swagger.yml are something like

```yml
paths:
  /foo:
    get:
      security:
      - AuthHeader: []
      responses:
        $ref: "common.yml#/components/scheas/FooBar"
components:
  securitySchemes:
     AuthHeader:
      $ref: "common.yml#/components/securitySchemes/AuthHeader"
```

External `schema` can be displayd using ReDoc.
However, it seems that external `security` is not displayed.
