### ISSUE TITLE
The simple object schema is not seen  

### ISSUE THREAD

**Issue by Bettenbuk** [Redocly/redoc#864]
The simple object schema is not seen, for example:

``` YAML
...
schemas:
 x: 
  type: array
  items: object
 y:
  type: object
``` 
In the response and the request body y is not displayed and x is seen as an empty array.
