### ISSUE TITLE
can't manage to display double quotes without slashes

### ISSUE THREAD

**Issue by user3160** [Redocly/redoc#934]
```
example: |
          &filter={"company_id":"3"}
```

is rendered as 
Example: `"&filter={\"company_id\":\"3\"}\n"`

how to get rid of escape slashes?

below is part of my spec

```
paths:
  /roles:
    get:
      parameters:
      - name: filter
        in: query
        required: false
        schema:
          type: object
          properties:
            company_id:
              type: string
            name:
              type: string
        example: |
          &filter={"company_id":"3"}
```

**Comment by RomanHotsiy** [comment]
This is a bug in Redoc.

**Comment by RomanHotsiy** [comment]
Implemented json serialization support.

See details here: https://swagger.io/docs/specification/describing-parameters/#schema-vs-content

In your case, use:
```yaml
paths:
  /roles:
    get:
      parameters:
        - name: filter
          in: query
          required: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  company_id:
                    type: string
                  name:
                    type: string
          example: {"company_id":"3"}
```

It will land in the upcoming version `2.0.0-rc.13`
