### ISSUE TITLE
Wrong description on same nested schema properties. 

### ISSUE THREAD

**Issue by martnst** [Redocly/redoc#936]
Setup: Same named properties have different meaning in our model, hence come with a different description in our schema. ReDoc displays the parents property's description on any nested occurrences. I have striped everything from our project to get a minimal example. In our project it actually goes even 3 levels deep. 

![image](https://user-images.githubusercontent.com/3084607/59053442-bf24b480-8891-11e9-9a0c-67ad0d58ec38.png)

**Files:** 

*index.html:*
```
<!DOCTYPE html>
<html>

<head>
  <title>ReDoc</title>
  <!-- needed for adaptive design -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

  <!--
    ReDoc doesn't change outer page styles
    -->
  <style>
    body {
      margin: 0;
      padding: 0;
    }
  </style>
</head>

<body>
  <!-- <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc> -->
  <redoc spec-url='/openapi.yml'></redoc>
  <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
</body>

</html>
```

*openapi.yml:*
```
openapi: 3.0.0
info:
  title: Deployed APIs
  version: 1.0.0
servers:
- url: http://ebalance-test-api.sloppy.zone/backend

paths:
  /menuplans/{id}:
    get:
      operationId: Get Menuplan by ID
      responses:
        200:
          description: default response
          content:
            application/json:
              schema: 
                $ref: '/schemas/menuplan.yml'
```

*schemas/menuplan.yml*
```
$schema: http://json-schema.org/draft-07/schema
id: menuplan
type: object
properties:
  id: 
    type: string
  nutritions: 
    description: AAA Sum  of all meal's nutritions for this plan. 
    $ref: 'nutritions.yml'
  breakfast:     
    $ref: 'meal.yml'
  lunch: 
    $ref: 'meal.yml'
  dinner: 
    $ref: 'meal.yml'
```

*schemas/meal.yml*
```
$schema: http://json-schema.org/draft-07/schema
id: meal
type: object
properties:
  id: 
    type: string
  nutritions: 
    description: BBB Sum of all nutritions eaten with the meal.
    $ref: 'nutritions.yml'
```

*schemas/nutritions.yml*
````
$schema: http://json-schema.org/draft-07/schema
id: nutritions
type: object
description: List of all nutritons a food, recipe or meal has.
properties:
  energy: 
    description: energy in kcal
    type: number
    format: float
  protein: 
    description: protein in gram
    type: number
    format: float
  carbohydrates: 
    description: carbohydrates in gram
    type: number
    format: float
  fat: 
    description: fat in gram
    type: number    
    format: float
```

**Comment by martnst** [comment]
![image](https://user-images.githubusercontent.com/3084607/59054115-4cb4d400-8893-11e9-9ee5-7f6bbe6c6078.png)

Here is another example, which should look like this in code: 

```
  nutritions: 
    description: Sum of all nutritions of all ingredients
    $ref: 'nutritions.yml'
  nutritionsPerPortion:
    description: Sum of all nutritions of all ingredients per portion
    $ref: 'nutritions.yml'
```
