### ISSUE TITLE
Example times/dates in OpenAPI changed by Redoc

### ISSUE THREAD

**Issue by ElizabethM-fourth** [Redocly/redoc#947]
Hello,
I have some fields in a response that use a time format. ReDoc is changing the examples in the output. Here's the OpenAPI file:

        ContainerName:
          type: string
          description: Internal filename.
          example: 2018-03-12
        ModifiedDateTime:
          type: string
          description: The day and time the file was last modified in Fourth, in ISO 8601 format.
          example: 2018-03-12T12:43:53

And attached is a screenshot showing how ReDoc is "reinterpreting" my example. 

<img width="235" alt="why-redoc-why" src="https://user-images.githubusercontent.com/37876863/59752870-e65c8800-927a-11e9-9df5-c2c7f97465e5.png">

This shouldn't happen - the example should obviously show as written, so as to be accurate.

Please let me know if this is something that can/will be resolved.

Thanks, Elizabeth

**Comment by RomanHotsiy** [comment]
Wrap you examples in quotes:

```yaml
    ContainerName:
      type: string
      description: Internal filename.
      example: "2018-03-12"
    ModifiedDateTime:
      type: string
      description: The day and time the file was last modified in Fourth, in ISO 8601 format.
      example: "2018-03-12T12:43:53"
```

That's caused by yaml special treatment of time strings. There is nothing Redoc can do here.
