### ISSUE TITLE
Hide http method in sidebar

### ISSUE THREAD

**Issue by raderio** [Redocly/redoc#981]
Add possibility to hide http method in sidebar, so only description will be displayed.
![redoc](https://user-images.githubusercontent.com/4563564/61589972-31d7be00-abba-11e9-9cc1-4bbea2cee9ef.png)

**Comment by nanov** [comment]
this could be easily achieved with css, adding some style like this : 
```css
.operation-type {
    display: none;
}
```
