### ISSUE TITLE
Incorrect render pipeDelimited array

### ISSUE THREAD

**Issue by Yalieee** [Redocly/redoc#990]
Hi, could you help check is this a bug in redoc? 

# Example
```yml
parameters:
  - in: query
    name: ids
    style: pipeDelimited
    explode: false
    schema:
      type: array
      items:
        type: string
        example: [10-A12345, 10-22]
```

# Result
![螢幕快照 2019-07-31 下午2 58 14](https://user-images.githubusercontent.com/13540526/62190345-b3420400-b3a3-11e9-8025-826a42e38784.png)

Example: `ids=10-A12345,10-22`

# Expected Result
According to [serialization](https://swagger.io/docs/specification/serialization/), the delimiter should be pipe. So, `ids=10-A12345|10-22`

# Version
2.0.0-rc.13

**Comment by RomanHotsiy** [comment]
Your example is on the wrong level. Move it to array level:

```yaml
parameters:
  - in: query
    name: ids
    style: pipeDelimited
    explode: false
    schema:
      type: array
      example: [10-A12345, 10-22]
      items:
        type: string
```
